name: coverage
on: push
jobs:
    coveralls:
        runs-on: ubuntu-latest
        steps:
            - name: Coveralls GitHub Action
              uses: coverallsapp/github-action@v2
              with:
                github-token: ${{ github.token }}

