# Team: CSE 110 SP23 Team 28, UC Sussy Developers
# Date: 5/19/2023
# Authors: Cody Rupp
# Description: CI/CD tester workflow for automatic testing on baeometer

name: Jest
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18"

      # Install required deps for action
      - name: Install Dependencies
        run: cd source; npm install

      # Finally, run our tests
      - name: Run Tests
        run: cd source; npm test